a=input("enter a value")
b=input("enter b value")
c=input("enter c value")
x=input("enter x value")
d=int(a)
e=int(b)
f=int(c)
g=int(x)
print(d*(g**2)+e*g+f)
print(d*(g**5)+e*(g**3)+f)
print((d*g+e)/(d*g-e))

